### ISSUE TITLE
支持E73-2G4M08S1？

### ISSUE THREAD

**Issue by XSJFYZS** [ziteh/mdbt-micro#15]
你好开发者
首先感谢你分享的开源项目
我正在制作1个无线轨迹球项目，但MDBT50Q在国内大陆很难购买，而E73-2G4M08S1C只需要15元人民币而已
我还想添加一个编码器用于网页滚动\音量控制
请问这个模块是否可以支持？谢谢

**Comment by ziteh** [comment]
Hi
MDBT Micro 僅支援 MDBT50Q，如果你想要使用 E73 的話，推薦 [joric/nrfmicro](https://github.com/joric/nrfmicro)
它的 wiki 内有很詳細的介紹

也可以看看 SuperMini NRF52840

**Comment by XSJFYZS** [comment]
> 你好 MDBT Micro 仅支持 MDBT50Q，如果你想使用 E73 的话，推荐[joric/nrfmicro](https://github.com/joric/nrfmicro) 它的 wiki 内有很详细的介绍
> 
> 也可以看看 SuperMini NRF52840

谢谢回复，我先学习一下

**Comment by ziteh** [comment]
Close inactive issue, and please feel free to reopen it if needed : )
